# Application Name
spring.application.name=anycall-example-consumer

# Server Port
server.port=8080

# Redis Configuration
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# AnyCall Configuration
anycall.timeout=30s
anycall.metrics-enabled=true

# Logging Configuration
logging.level.kaiquebt.dev.anycall=INFO
logging.level.root=INFO
